### PR TITLE
Fixed StyleCop on Mono 4

### LINKED ISSUE #8015: `make check` fails under mono 4.0
Mono 4.0 removes the 3.5 build targets that Stylecop (or maybe stylecopplus?) is compiled against. I expect this will break travis once the official release is pushed to the repos.

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at OpenRA.Mods.Common.UtilityCommands.CheckCodeStyle.Run (OpenRA.ModData modData, System.String[] args) [0x00087] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//UtilityCommands/CheckCodeStyle.cs:39 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015a] in /Users/paul/src/OpenRA/OpenRA.Utility//Program.cs:54 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at OpenRA.Mods.Common.UtilityCommands.CheckCodeStyle.Run (OpenRA.ModData modData, System.String[] args) [0x00087] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//UtilityCommands/CheckCodeStyle.cs:39 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015a] in /Users/paul/src/OpenRA/OpenRA.Utility//Program.cs:54 
make: *** [check] Error 1
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12001271-make-check-fails-under-mono-4-0?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://github.com/OpenRA/OpenRA/issues/8015.

We need MSBuild in the .NET Framework 3.5 version. Mono 4 dropped those so we need to manually install them as a dependency now. I consider this a workaround until we replace this with something modern probably https://github.com/dotnet/roslyn based in the future.

### CODE REVIEW

**Comment by akoeplinger** [comment]
You realize that the MSBuild on nuget is actually 14.1 (the one open-sourced by MS)?
Why can't you just reference Mono's 12.0/14.0 Microsoft.Build.Framework.dll ?

**Comment by Mailaender** [comment]
The Mono 4 supplied ones are not of much help.

```
error CS1701: Warning as Error: Assuming assembly reference `Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' matches assembly `Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. You may need to supply runtime policy
```

```
error CS1701: Warning as Error: Assuming assembly reference `Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' matches assembly `Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. You may need to supply runtime policy
```

I am a bit lost now. Looks like DLL hell just got ported to Unix to me.

**Comment by akoeplinger** [comment]
Ah, I see, the reference to 3.5 Microsoft.Build.Framework comes from stylecop. I think you can ignore the warning and add bindingRedirects to redirect to the 4.0 assemblies at runtime.

**Comment by Mailaender** [comment]
How do you supply such runtime policys the compiler is talking about?

**Comment by akoeplinger** [comment]
@Mailaender https://msdn.microsoft.com/en-us/library/eftw1fys(v=vs.110).aspx, e.g.:

``` xml
<dependentAssembly>
    <assemblyIdentity name="Microsoft.Build.Framework"
publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-100.0.0.0" newVersion="12.0.0.0" />
</dependentAssembly>
```


This only works for the assemblies that haven't changed their name though, e.g. not for Microsoft.Build.Utilities.v3.5.dll (which was an atrocious decision they finally fixed in MSBuild 14).

**Comment by Mailaender** [comment]
Thanks. Updated with a simple `XML` file instead of several megabytes of redundant nuget dependencies.

**Comment by pchote** [comment]
:+1: works for me on OS X.

**Comment by obrakmann** [comment]
:+1: here too
