### PR TITLE
Preallocate dictionary size in ToDictionaryWithConflictLog

### PR DESCRIPTION
**Pull request by RoosterDragon**
This saves some allocations in MiniYaml parsing on startup, but with also benefit other callers of the method.

### CODE REVIEW

**Comment by RoosterDragon** [comment]
I suspect the build failure will be solved by #19902

**Comment by abcdefg30** [comment]
> I suspect the build failure will be solved by #19902

Only the build compiling with Mono is failing:
> Exts.cs(410,11): error CS1061: 'IEnumerable<TSource>' does not contain a definition for 'TryGetNonEnumeratedCount' and no accessible extension method 'TryGetNonEnumeratedCount' accepting a first argument of type 'IEnumerable<TSource>' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/OpenRA/OpenRA/OpenRA.Game/OpenRA.Game.csproj]

Does Mono not contain this method?

**Comment by teinarss** [comment]
No, it was added in net 6.

**Comment by abcdefg30** [comment]
Then we might need to add a Mono only path that uses the old code.

**Comment by RoosterDragon** [comment]
Switched to a cast on `ICollection<T>` which suffices for our purposes.

**Comment by penev92** [comment]
Makes sense 👍

File: OpenRA.Game/Exts.cs [hunk 1]
```diff
@@ -432,8 +433,6 @@ public static HashSet<T> ToHashSet<T>(this IEnumerable<T> source)
 					dupKeyMessages.Add(logValue(element));
 					continue;
```
Comment (abcdefg30) [inline OpenRA.Game/Exts.cs]: This can/should be removed now.

Comment (RoosterDragon) [reply OpenRA.Game/Exts.cs]: Removed

**Review by abcdefg30 — APPROVED** [review]

**Comment by abcdefg30** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/bcb8af40f97a394ae8bc37f65dfc7a0d037c4d95...35218d51d3516a4ba77ce04cf0982d3444a71a50)
