### PR TITLE
Fixed a compilation error on Mono 2.10

### PR DESCRIPTION
**Pull request by Mailaender**
Again revealed accidentally by https://build.opensuse.org/package/show/games:openra/development. Introduced by https://github.com/OpenRA/OpenRA/pull/8065.

### CODE REVIEW

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/rdiff/games:openra/playtest?linkrev=base&rev=19
