### PR TITLE
Let Railgun implement ISync

### PR DESCRIPTION
**Pull request by abcdefg30**
Resolves the `OpenRA.Utility(1,1): Warning: OpenRA.Mods.Common.Projectiles.Railgun has members with the Sync attribute but does not implement ISync` errors we currently have on bleed. (Which is a regression from #18009.)

### CODE REVIEW

**Review by obrakmann — APPROVED** [review]

**Comment by obrakmann** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/48e666f455ce47142796efad202df71b867758e7)
